{
  description = "Flake utils demo";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    ignis = {
      url = "github:ignis-sh/ignis";
      # ! Important to override
      # Nix will not allow overriding dependencies if the input
      # doesn't follow your system pkgs
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, ignis }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        ignisDeps = ignis.packages.${system}.ignis.override {
          enableAudioService = true;
          enableBluetoothService = true;
          enableNetworkService = true;
          enableRecorderService = true;
          useDartSass = true;

          extraPackages = with pkgs; [
            # dart-sass
          ];
        };

        # desktop-derivation now directly holds the ignis-desktop python package
        ignis-desktop = import ./nix/pkgs/desktop.nix {
          inherit pkgs ignisDeps;
          src = self;
        };
      in
      rec {
        packages = rec {
          inherit ignis-desktop; # ignis-desktop is now the python package
          ignis = ignisDeps;
          default = ignis-desktop; # Default now builds the python package
        };
        apps = rec {
          # The executable is now generated by setuptools within the python package
          # and not directly created as a Nix app.
          # To run, one would need to activate the shell and run "ignis-desktop".
          # If they build the default app, it will be the python package.
          # The original idea was to avoid Nix-generated shell scripts.
          default = flake-utils.lib.mkApp { drv = packages.ignis-desktop; };
        };
        devShell = pkgs.mkShell {
          buildInputs = with pkgs; [
            gtk3
            gtk4
            glib
          ];
          nativeBuildInputs = with pkgs; [
            (python3.withPackages(ps: with ps; [
              ipython
              gobject-introspection
              pygobject3
              pygobject-stubs
              ignis-desktop # The newly built python package
            ]))
            basedpyright
            gobject-introspection
            ignisDeps # ignis itself, if needed in the shell.
          ];
          shellHook = ''
            export GI_TYPELIB_PATH="${pkgs.gtk3}/lib/girepository-1.0:${pkgs.gtk4}/lib/girepository-1.0:${pkgs.glib}/lib/girepository-1.0:$GI_TYPELIB_PATH"
          '';
        };
      }
    ) //
    {
nixosModules =
          let mod = import ./nix/modules/nixos { inherit self; };
          in {
            default = mod;
            ignis-desktop = mod;
          };
        homeManagerModules =
          let mod = import ./nix/modules/home-manager { inherit self; };
          in {
            default = mod;
            ignis-desktop = mod;
          };
    };
}
